give @s ml_mod:spawner_marker_1 64
give @s ml_mod:spawner_marker_2 64
give @s ml_mod:spawner_marker_3 64
give @s ml_mod:spawner_marker_4 64
give @s ml_mod:spawner_marker_5 64
give @s ml_mod:spawner_marker_6 64
give @s ml_mod:spawner_marker_7 64
give @s ml_mod:spawner_marker_8 64
give @s ml_mod:spawner_marker_9 64
give @s ml_mod:spawner_marker_spawn 64
